### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by jonschreiber** [RahulMR42/oci-devops-deploy-on-kube-using-instancegroup#1]
https://github.com/RahulMR42/oci-devops-deploy-on-kube-using-instancegroup/blob/9131862394dbffcec895dcaccf8206717699f60b/README.md?plain=1#L36

show be "Allow..." 

but couldn't we just have one set our policy statements? ie 
`Allow dynamic-group mr-telesis-private-dg-devops-instances to manage repos in compartment <compartment_name>`

but not ... `mr-prod-compartment`

**Comment by RahulMR42** [comment]
Fixed ,thank you
